# версия docker-compose
version: '3.8'

# имя директории для хранения данных
volumes:
  postgres_data:

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:12.4
    # volume и связанная с ним директория в контейнере
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # адрес файла, где хранятся переменные окружения
    env_file:
      - ./.env
  web:
    build: .
    restart: always

    command: bash -c "python manage.py collectstatic --noinput && python manage.py makemigrations --noinput && python manage.py migrate --noinput && python manage.py import_ingred && gunicorn backend.wsgi:application --bind 84.201.179.160:8020"
    ports:
      - "8020:8020"
    depends_on:
      - db
    env_file:
      - ./.env
  nginx: 
    image: nginx:1.19.3
    volumes:
      - ./nginx:/nginx/conf
      - ./static:/static

    ports:
      - "80:80"
    depends_on:
      - web
    
